spring:
  r2dbc:
    url: r2dbc:pool:mysql://47.94.45.138:3306/halodb
#    url: r2dbc:pool:mysql://47.94.45.138:3306/halodb_dev
    username:
    password:
  sql:
    init:
      mode: always
      platform: mysql
